# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!
  # Pods for GlovoChallenge
  pod 'R.swift','~> 3.3.0'
  pod 'Alamofire'
  pod 'SVProgressHUD', '~> 2.2.2'
  pod 'GoogleMaps', '~> 2.5.0'
  pod 'GooglePlaces'
  pod 'ISHPullUp'

target 'GlovoChallengeDev' do
    end
target 'GlovoChallengeProd' do
end
  target 'GlovoChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GlovoChallengeUITests' do
    inherit! :search_paths
    # Pods for testing
  end
